#!/bin/bash

# Author:
#   Simon Pfaff, simon.pfaff@stud-mail.uni-wuerzburg.de
#   Thomas Hackl, thomas.hackl@uni-wuerzburg.de
#
# Last Modified: Simon Pfaff, 2014-09-02

# Version 0.2 

#SeqChunker-dd need Bash Version 4 or higher, fallback to slower sed version

VER=`bash --version | grep -Eo [0-9][.][0-9] | cut -d. -f1`

Bin="$(cd -- "$(dirname "$0")" && pwd)"

if [ "$VER" -ge 4 ]; then

    bash "$Bin/SeqChunker-dd" $@
    
else

    bash "$Bin/SeqChunker-sed" $@
    echo "#Bash Version older than 4.0, using SeqChunker-sed"
fi;
